#!/usr/bin/env python3
# PROOF: [L2/インフラ] <- mekhane/symploke/report_generator.py
# PURPOSE: Phantazein セッション統合レポートを Markdown テンプレートから生成する
"""
Report Generator — セッション統合レポートの動的生成。

get_report_data() の出力 (Python dict) を Markdown 文字列に変換する。
LLM は使用せず、テンプレートベースで再現性を保証する。
"""

import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Optional

logger = logging.getLogger("hegemonikon.report_generator")

JST = timezone(timedelta(hours=9))


# PURPOSE: Unix timestamp を JST 文字列に変換する
def _ts_to_str(ts: float, fmt: str = "%Y-%m-%d %H:%M") -> str:
    """Unix timestamp を JST 文字列に変換する。"""
    if not ts or ts == 0.0:
        return "N/A"
    return datetime.fromtimestamp(ts, tz=JST).strftime(fmt)


# PURPOSE: バイト数を人間が読める形式に変換する
def _human_bytes(size: int) -> str:
    """バイト数を KB/MB 表記に変換する。"""
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    else:
        return f"{size / (1024 * 1024):.1f} MB"


# PURPOSE: レポートデータから Markdown レポートを生成する
def render_report(data: dict, *, title: str = "") -> str:
    """get_report_data() の出力から Markdown レポートを生成する。

    Args:
        data: get_report_data() が返す辞書。
        title: レポートタイトル (省略時は自動生成)。

    Returns:
        Markdown 形式のレポート文字列。
    """
    period = data.get("period", {})
    summary = data.get("summary", {})
    sessions = data.get("sessions", [])
    breakdown = data.get("artifact_breakdown", {})
    orphans = data.get("orphan_artifacts", [])
    timeline = data.get("timeline", [])

    days = period.get("days", 1)
    end_ts = period.get("end", 0.0)

    if not title:
        date_str = _ts_to_str(end_ts, "%Y-%m-%d")
        title = f"セッション統合レポート ({date_str})"
        if days > 1:
            start_str = _ts_to_str(period.get("start", 0.0), "%Y-%m-%d")
            title = f"セッション統合レポート ({start_str} ~ {date_str})"

    lines: list[str] = []

    # ── §0 ヘッダ ──────────────────────────────────────────
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"> 生成日時: {_ts_to_str(end_ts, '%Y-%m-%d %H:%M:%S JST')}")
    lines.append(f"> 対象期間: {days}日間")
    lines.append(f"> Generated by Phantazein Report Generator v1.0")
    lines.append("")

    # ── §1 サマリ KPI ──────────────────────────────────────
    lines.append("## §1 サマリ KPI")
    lines.append("")
    lines.append("| 指標 | 値 |")
    lines.append("|---|---|")
    lines.append(f"| セッション総数 | {summary.get('total_sessions', 0)} |")
    lines.append(f"| アクティブセッション (artifact > 0) | {summary.get('active_sessions', 0)} |")
    lines.append(f"| アーティファクト総数 | {summary.get('total_artifacts', 0)} |")
    lines.append(f"| Handoff 総数 | {summary.get('total_handoffs', 0)} |")
    lines.append(f"| ROM 総数 | {summary.get('total_roms', 0)} |")
    lines.append(f"| Handoff カバレッジ | {summary.get('handoff_coverage', 0.0)}% |")
    lines.append("")

    # Handoff カバレッジ警告
    coverage = summary.get("handoff_coverage", 0.0)
    if coverage < 50.0:
        lines.append("> [!CAUTION]")
        lines.append(f"> Handoff カバレッジが {coverage}% と低い。/bye 未実行セッションが多数存在。")
        lines.append("")

    # ── §2 セッション一覧 ──────────────────────────────────
    lines.append("## §2 セッション一覧")
    lines.append("")

    if not sessions:
        lines.append("_対象期間内にセッションが見つかりませんでした。_")
        lines.append("")
    else:
        lines.append("| # | セッション ID (先頭8文字) | タイトル | 開始 | Art | HO | ROM | PJ |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for i, s in enumerate(sessions, 1):
            sid = s.get("id", "")[:8]
            stitle = (s.get("title") or "無題")[:40]
            created = _ts_to_str(s.get("created_at", 0.0), "%H:%M")
            art_count = s.get("artifact_count") or 0
            ho_count = len(s.get("handoffs", []))
            rom_count = len(s.get("roms", []))
            pj_count = len(s.get("projects", []))
            ho_mark = f"✅ {ho_count}" if ho_count > 0 else "❌ 0"
            lines.append(f"| {i} | `{sid}` | {stitle} | {created} | {art_count} | {ho_mark} | {rom_count} | {pj_count} |")
        lines.append("")

    # ── §3 アーティファクト分類 ────────────────────────────
    lines.append("## §3 アーティファクト分類")
    lines.append("")

    if not breakdown:
        lines.append("_アーティファクトが見つかりませんでした。_")
        lines.append("")
    else:
        lines.append("| タイプ | 数 | 合計サイズ |")
        lines.append("|---|---|---|")
        total_count = 0
        total_bytes = 0
        for atype in sorted(breakdown.keys()):
            info = breakdown[atype]
            cnt = info["count"]
            bts = info["total_bytes"]
            total_count += cnt
            total_bytes += bts
            lines.append(f"| {atype} | {cnt} | {_human_bytes(bts)} |")
        lines.append(f"| **合計** | **{total_count}** | **{_human_bytes(total_bytes)}** |")
        lines.append("")

    # ── §4 Orphan アーティファクト ─────────────────────────
    lines.append("## §4 Orphan アーティファクト (≥ 5KB)")
    lines.append("")

    if not orphans:
        lines.append("_永続化漏れの候補は検出されませんでした。_ ✅")
        lines.append("")
    else:
        lines.append(f"> [!WARNING]")
        lines.append(f"> {len(orphans)} 件の大型カスタムアーティファクトが検出されました。永続化を検討してください。")
        lines.append("")
        lines.append("| ファイル名 | セッション | サイズ |")
        lines.append("|---|---|---|")
        for o in orphans:
            fname = o.get("filename", "?")
            sess = (o.get("session_title") or o.get("session_id", ""))[:30]
            sz = _human_bytes(o.get("size_bytes", 0))
            lines.append(f"| {fname} | {sess} | {sz} |")
        lines.append("")

    # ── §5 Handoff カバレッジ詳細 ──────────────────────────
    lines.append("## §5 Handoff カバレッジ詳細")
    lines.append("")

    no_handoff_sessions = [s for s in sessions if not s.get("has_handoff", False)]
    if no_handoff_sessions:
        lines.append(f"**Handoff なしセッション: {len(no_handoff_sessions)} 件**")
        lines.append("")
        for s in no_handoff_sessions:
            sid = s.get("id", "")[:8]
            stitle = (s.get("title") or "無題")[:40]
            lines.append(f"- `{sid}` — {stitle}")
        lines.append("")
    else:
        lines.append("_全セッションが Handoff を生成しています。_ ✅")
        lines.append("")

    # ── §6 タイムライン ────────────────────────────────────
    if timeline:
        lines.append("## §6 タイムライン (日別)")
        lines.append("")
        lines.append("| 日付 | セッション数 | アーティファクト総数 |")
        lines.append("|---|---|---|")
        for t in timeline:
            day = t.get("day", "?")
            sc = t.get("session_count", 0)
            ta = t.get("total_artifacts") or 0
            lines.append(f"| {day} | {sc} | {ta} |")
        lines.append("")

    # ── フッタ ─────────────────────────────────────────────
    lines.append("---")
    lines.append(f"*Phantazein Report Generator v1.0 — {_ts_to_str(end_ts)}*")
    lines.append("")

    return "\n".join(lines)


# PURPOSE: レポートを生成してファイルに保存する
def generate_and_save(
    data: dict,
    output_path: str,
    *,
    title: str = "",
) -> str:
    """レポートを生成し、指定パスに保存する。

    Args:
        data: get_report_data() の出力。
        output_path: 保存先のファイルパス。
        title: レポートタイトル。

    Returns:
        生成された Markdown 文字列。
    """
    from pathlib import Path

    md = render_report(data, title=title)
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(md, encoding="utf-8")
    logger.info("レポート保存: %s (%d bytes)", output_path, len(md))
    return md
